### PR TITLE
Add pvi changes to convert device command

### PR DESCRIPTION
**Pull request by marcelldls**
Tested with `deploy-local` and two cameras on bl01c. Await pvi, ibek release

### CODE REVIEW

**Review by gilesknap — APPROVED** [review]
That looks much better!

**Comment by marcelldls** [comment]
@gilesknap Am not happy to merge yet because the pvi changes are not merged/released. Currently override the `requirements.txt` but will remove it before setting this ready for review

**Comment by gilesknap** [comment]
@marcelldls can we merge this now? I did update PVI in ibek just last week so I think it is latest.

**Comment by gilesknap** [comment]
@marcelldls I believe this can merge now?

**Pull request merged**
